config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "concerts", to: "concerts#index"
  get "tournages", to: "tournages#index"
  get "artistiques", to: "artistiques#index"
  get "blog", to: "posts#index"
  resources :posts, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artistique.rb
class Artistique < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/tournage.rb
class Tournage < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  has_many :concerts, dependent: :destroy
  has_many :tournages, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artistiques_controller.rb
class ArtistiquesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @artistiques = Artistique.all
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @concerts = Concert.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, except: :new
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = User.first
    if @post.save!
      redirect_to blog_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:photos, :title, :content)
  end

end

app/controllers/tournages_controller.rb
class TournagesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @tournages = Tournage.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artistiques/index.html.erb
<div class="container text-center" data-controller="disable-button">

  <div class="banner_artistiques mb-5">
    <h1>Artistiques</h1>
  </div>

  <div class="grid-container mb-5">
    <%= link_to concerts_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-1 text-white">Concerts</div>
    <% end %>
    <%= link_to tournages_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-2 text-white">Tournages</div>
    <% end %>
    <%= link_to blog_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-4 text-white">Mon blog</div>
    <% end %>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleAbstrait">
      <div class="banner-abstrait">
        <h2>Abstrait</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="abstrait">
      <% @artistiques.find_by(title: "Abstrait").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleKodak">
      <div class="banner-kodak">
        <h2>Kodak TX400</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="kodak">
      <% @artistiques.find_by(title: "Kodak TX400").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#togglePortraits">
      <div class="banner-portraits">
        <h2>Portraits</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="portraits">
      <% @artistiques.find_by(title: "Portraits").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleStreet">
      <div class="banner-street">
        <h2>Street Photo</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="street">
      <% @artistiques.find_by(title: "Street Photo").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleArchitecture">
      <div class="banner-architecture">
        <h2>Architecture</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="architecture">
      <% @artistiques.find_by(title: "Architecture").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#togglePaysages">
      <div class="banner-paysages">
        <h2>Paysages</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="paysages">
      <% @artistiques.find_by(title: "Paysages").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleTextures">
      <div class="banner-textures">
        <h2>Textures</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="textures">
      <% @artistiques.find_by(title: "Textures").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

</div>

app/views/concerts/index.html.erb
<div class="container text-center" data-controller="disable-button" >

  <div class="banner_concerts mb-2">
    <h1>Concerts</h1>
  </div>


  <div class="grid-container mb-5 ">
    <%= link_to tournages_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-2 text-white">Tournages</div>
    <% end %>
    <%= link_to artistiques_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-3 text-white">Artistiques</div>
    <% end %>
    <%= link_to blog_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-4 text-white">Mon blog</div>
    <% end %>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleAura">
      <div class="banner-aura-noir">
        <h2>Aura Noir</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="aura">
      <% @concerts.find_by(title: "Aura Noir").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleHail">
      <div class="banner-hail-spirit-noir">
        <h2>Hail Spirit Noir</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="hail">
      <% @concerts.find_by(title: "Hail Spirit Noir").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleFeux">
      <div class="banner-feux-de-beltane">
        <h2>Les feux de Beltane</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="feux">
      <% @concerts.find_by(title: "Les feux de Beltane").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MadBasque</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner mb-3">
  <h1>Mad Basque Studio</h1>
  <p>Here we'll have a great catchphrase but not right now</p>
</div>

<div class="container text-center">

  <div class="container text-center">
    <div class="grid-container mb-5">
      <%= link_to concerts_path, class:"text-decoration-none menu-img" do %>
        <div class="grid-item-1 text-white">Concerts</div>
      <% end %>
      <%= link_to tournages_path, class:"text-decoration-none menu-img" do %>
        <div class="grid-item-2 text-white">Tournages</div>
      <% end %>
      <%= link_to artistiques_path, class:"text-decoration-none menu-img" do %>
        <div class="grid-item-3 text-white">Artistiques</div>
      <% end %>
      <%= link_to blog_path, class:"text-decoration-none menu-img" do %>
        <div class="grid-item-4 text-white">Mon blog</div>
      <% end %>
  </div>

  <div class="about ms-3 mb-5">
    <div class="about-fr">
      <h2>A propos de moi</h2>
      <p>
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      </p>
    </div>
    <div class="about-en">
      <h2>About me</h2>
      <p>
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      </p>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container text center">

  <div class="banner_blog mb-5 text-center">
    <h1>Blog</h1>
  </div>

  <div class="grid-container mb-5">
    <%= link_to concerts_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-1 text-white">Concerts</div>
    <% end %>
    <%= link_to tournages_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-2 text-white">Tournages</div>
    <% end %>
    <%= link_to artistiques_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-3 text-white">Artistiques</div>
    <% end %>
  </div>

  <% @posts.each do |post| %>
    <%= link_to post_path(post), class:"text-decoration-none text-black post-title" do %>
      <div class="text-center mb-5 single-post shadow-lg">
        <h2 class="mb-5"><%= post.title%></h2>
        <% post.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 500, width: 700, crop: :fill %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="text-center mb-2 pb-2">
    <%= link_to "Back to blog list", blog_path, class:"text-decoration-none" %>
  </div>

</div>

app/views/posts/new.html.erb
<div class="container text-center mb-5">
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :photos %>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post text-center">
    <h2 class="mb-5"><%= @post.title %></h2>
    <% @post.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 500, width: 700, crop: :fill %>
    <% end %>
    <p class="mt-5"><%= @post.content %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bg-black text-white">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github text-white"></i></a>
    <a href="#"><i class="fab fa-instagram text-white"></i></a>
    <a href="#"><i class="fab fa-facebook text-white"></i></a>
    <a href="#"><i class="fab fa-twitter text-white"></i></a>
    <a href="#"><i class="fab fa-linkedin text-white"></i></a>
  </div>
  <div class="footer-copyright">
    This will be the footer of the app with relevant infos
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon text-center mb-3">
   <h1><%=link_to "MAD BASQUE PHOTO", root_path, class: "text-decoration-none text-white"%></h1>
</div>

app/views/tournages/index.html.erb
<div class="container text-center" data-controller="disable-button">

  <div class="banner_tournages mb-5">
    <h1>Tournages</h1>
  </div>

  <div class="grid-container mb-5">
    <%= link_to concerts_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-1 text-white">Concerts</div>
    <% end %>
    <%= link_to artistiques_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-3 text-white">Artistiques</div>
    <% end %>
    <%= link_to blog_path, class:"text-decoration-none menu-img" do %>
      <div class="grid-item-4 text-white">Mon blog</div>
    <% end %>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleStone">
      <div class="banner-voyage-de-stone">
        <h2>Le voyage de Stone</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="stone">
      <% @tournages.find_by(title: "Le voyage de Stone").photos.each do |photo| %>
        <a href="<%= photo.url %>" target="_blank">
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </a>
      <% end %>
    </div>
  </div>

  <div class="mb-2">
    <a href="#" class="text-decoration-none" data-action="click->disable-button#toggleYetili">
      <div class="banner-yetili">
        <h2>Yetili</h2>
      </div>
    </a>

    <div class="photo_grid mb-5 d-none" data-disable-button-target="yetili">
      <% @tournages.find_by(title: "Yetili").photos.each do |photo| %>
      <a href="<%= photo.url %>" target="_blank">
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      </a>
      <% end %>
    </div>
  </div>

</div>